### ISSUE TITLE
Allow to star repos/suffixes, and display in a Starred page

### ISSUE THREAD

**Issue by pingpongboss** [material-motion/milemarker#15]
I care about -android, starmap, and team. Switching suffixes often is time consuming.

**Comment by jverkoey** [comment]
Going to take a stab at this.

Will try adding a "star" button to every filterable node.

**Comment by jverkoey** [comment]
Everything that's filterable now has a star. The star can be toggled.

Next step is to add/remove the filterable entity to local storage.

**Comment by jverkoey** [comment]
![screen shot 2016-07-12 at 1 20 48 am](https://cloud.githubusercontent.com/assets/45670/16755878/e2d03adc-47ce-11e6-9793-1716025cdae0.png)

**Comment by jverkoey** [comment]
Star states are now persisted locally.

Next step is to build a filter tab for starred entities.

**Comment by jverkoey** [comment]
Filter tab now exists, but needs custom logic for filtering.

**Comment by jverkoey** [comment]
![screen shot 2016-07-12 at 1 51 52 am](https://cloud.githubusercontent.com/assets/45670/16756468/3cc8c4ec-47d3-11e6-9c52-521b6af3f353.png)

W00t! Working version done.

**Comment by jverkoey** [comment]
Will file follow-up issue to track obvious bugs.

**Comment by pingpongboss** [comment]
Das pretty sweet
