### ISSUE TITLE
PM requests for prioritization management

### ISSUE THREAD

**Issue by jverkoey** [material-motion/milemarker#23]
Each milestone needs:
- Priority

**Comment by KatyKasmai** [comment]
Time to completion
Owner (person working on it)
Status (In progress/Completed on mm/dd)

**Comment by KatyKasmai** [comment]
Estimated date of completion (potential variation of Time to completion)

**Comment by jverkoey** [comment]
This is now available in the roadmap tab: https://material-motion.github.io/material-motion-milemarker/roadmap.html?filterby=appleos
