### ISSUE TITLE
Rename to material-motion-milemarker

### ISSUE THREAD

**Issue by appsforartists** [material-motion/milemarker#3]
Hooray naming conventions!

**Comment by jverkoey** [comment]
Oh yeah!

**Comment by jverkoey** [comment]
So, for projects that aren't strictly related to what we're building here I think the naming conventions may not be as applicable.

E.g. this tool could very easily work for any org.

Thoughts?

**Comment by jverkoey** [comment]
In that manner of thinking it probably should live in material-foundation.

**Comment by appsforartists** [comment]
material-motion is hardcoded in a number of places right now.  So long as that's true, it really is the material-motion-milemarker.

Of course, you could factor out the common parts into a reusable component, but it depends on how much flexibility you want, going forward, to make changes that specifically benefit our team.

**Comment by jverkoey** [comment]
Here's one potential plan:
- [ ] Move the repo to material-foundation. Call it milemarker.
- [ ] Remove the configuration assumptions in the material-foundation repo. Provide a clear place to fill things out.
- [ ] Fork the material-foundation repo to material-motion. Call it material-motion-milemarker.
- [ ] Make a local modification to our fork with the configuration.
- [ ] Deploy the code to gh-pages.

This gives a healthy balance of configuration, minimal overhead, and the ability for others to hack on the project as well.
